"""cria tabela professionals

Revision ID: 3b22e170e45c
Revises: e4cf942c3fc8
Create Date: 2026-05-02 17:26:38.349894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b22e170e45c'
down_revision: Union[str, Sequence[str], None] = 'e4cf942c3fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('service_area_km', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('total_services', sa.Integer(), nullable=False),
    sa.Column('completed_services', sa.Integer(), nullable=False),
    sa.Column('cancelled_services', sa.Integer(), nullable=False),
    sa.Column('punctuality_score', sa.Float(), nullable=False),
    sa.Column('months_active', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_user_id'), 'professionals', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professionals_user_id'), table_name='professionals')
    op.drop_table('professionals')
    # ### end Alembic commands ###
